import type { SiteProcessInputType } from '../../../..';
export declare function process_codeCard_like(input: SiteProcessInputType): void;
export declare function process_codeCard_like_free(input: SiteProcessInputType): void;
export declare function process_codeCard_like_head(input: SiteProcessInputType): void;
export declare function process_codeCard_like_like(input: SiteProcessInputType): void;
export declare function process_codeCard_like_list(input: SiteProcessInputType): void;
export declare function process_codeCard_like_mesh(input: SiteProcessInputType): void;
export declare function process_codeCard_like_nestedChildren(input: SiteProcessInputType): void;
export declare function process_codeCard_like_take(input: SiteProcessInputType): void;
export declare function process_codeCard_like_term(input: SiteProcessInputType): void;
