import code from '../../../index.js';
export declare function load_codeCard_bond(load: code.MeshLoad): void;
export declare function load_codeCard_bond_code(load: code.MeshLoad): void;
export declare function load_codeCard_bond_comb(load: code.MeshLoad): void;
export declare function load_codeCard_bond_loan(load: code.MeshLoad): void;
export declare function load_codeCard_bond_mark(load: code.MeshLoad): void;
export declare function load_codeCard_bond_move(load: code.MeshLoad): void;
export declare function load_codeCard_bond_nestedChildren(load: code.MeshLoad): void;
export declare function load_codeCard_bond_read(load: code.MeshLoad): void;
export declare function load_codeCard_bond_term(load: code.MeshLoad): void;
export declare function load_codeCard_bond_text(load: code.MeshLoad): void;
export declare function load_codeCard_bond_wave(load: code.MeshLoad): void;
