import { SiteDependencyObserverParentType, SiteDependencyObserverType, SiteProcessInputType } from '~';
export declare function addDependencyTreeObserver(input: SiteProcessInputType, list: Array<SiteDependencyObserverType>): void;
export declare function canResolveDependencyTree(input: SiteProcessInputType, list: Array<SiteDependencyObserverType>): boolean;
export declare function connectDependency(parent: SiteDependencyObserverType, binding: SiteDependencyObserverParentType, child: SiteDependencyObserverType): void;
export declare function getLeafDependencyList(tree: SiteDependencyObserverType, array?: Array<SiteDependencyObserverType>): Array<SiteDependencyObserverType>;
export declare function resolveDynamicPathDependencyTree(input: SiteProcessInputType): SiteDependencyObserverType;
export declare function resolveDynamicTermDependencyTree(input: SiteProcessInputType): SiteDependencyObserverType;
export declare function resolvePathDependencyTree(input: SiteProcessInputType): SiteDependencyObserverType;
export declare function resolvePluginDependencyTree(input: SiteProcessInputType): SiteDependencyObserverType;
export declare function resolveStaticPathDependencyTree(input: SiteProcessInputType): SiteDependencyObserverType;
export declare function resolveStaticTermDependencyTree(input: SiteProcessInputType): SiteDependencyObserverType;
export declare function resolveTermDependencyTree(input: SiteProcessInputType): SiteDependencyObserverType;
export declare function resolveTextDependencyTree(input: SiteProcessInputType): SiteDependencyObserverType;
