import { SiteProcessInputType } from '../index.js';
import type { SiteEnvironmentType } from '../index.js';
import { Base } from '../form/base.js';
export * from '../form/base.js';
export * from './card.js';
export declare function assertEnvironment(object: unknown): asserts object is SiteEnvironmentType;
export declare function createBase(): Base;
export declare function createEnvironment(bindings: Record<string, unknown>, parent?: SiteEnvironmentType): SiteEnvironmentType;
export declare function getEnvironmentProperty(environment: SiteEnvironmentType, name: string | number | symbol): unknown;
export declare function getEnvironmentVariable(base: Base, key: string): unknown;
export declare function hasEnvironmentVariable(environment: SiteEnvironmentType, name: string | number | symbol): boolean;
export declare function isEnvironment(object: unknown): object is SiteEnvironmentType;
export declare function setCachedFile(base: Base, path: string, content: string): void;
export declare function setEnvironmentProperty(scope: SiteEnvironmentType, property: string, value: unknown): void;
export declare function setEnvironmentVariable(base: Base, key: string, value: unknown): void;
export declare function withEnvironment(input: SiteProcessInputType, bindings: Record<string, unknown>): SiteProcessInputType;
