import type { SiteProcessInputType } from '../../../index.js';
export * from './bear/index.js';
export * from './face/index.js';
export * from './link/index.js';
export * from './mint/index.js';
export * from './term/index.js';
export * from './test/index.js';
export declare function process_deckCard_deck(input: SiteProcessInputType): void;
export declare function process_deckCard_deck_nestedChildren(input: SiteProcessInputType): void;
export declare function process_deckCard_deck_nestedTerm(input: SiteProcessInputType): void;
