import type { SiteProcessInputType } from '../../../..';
export declare function process_codeCard_bond(input: SiteProcessInputType): void;
export declare function process_codeCard_bond_code(input: SiteProcessInputType): void;
export declare function process_codeCard_bond_comb(input: SiteProcessInputType): void;
export declare function process_codeCard_bond_loan(input: SiteProcessInputType): void;
export declare function process_codeCard_bond_mark(input: SiteProcessInputType): void;
export declare function process_codeCard_bond_move(input: SiteProcessInputType): void;
export declare function process_codeCard_bond_nestedChildren(input: SiteProcessInputType): void;
export declare function process_codeCard_bond_read(input: SiteProcessInputType): void;
export declare function process_codeCard_bond_term(input: SiteProcessInputType): void;
export declare function process_codeCard_bond_text(input: SiteProcessInputType): void;
export declare function process_codeCard_bond_wave(input: SiteProcessInputType): void;
